# Generated by Django 5.1 on 2024-08-29 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('expected_output', models.CharField(max_length=255)),
                ('output_indicators', models.CharField(max_length=255)),
                ('year1_target', models.IntegerField()),
                ('year2_target', models.IntegerField()),
                ('year3_target', models.IntegerField()),
                ('year4_target', models.IntegerField()),
                ('year5_target', models.IntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('responsibility', models.CharField(max_length=255)),
                ('support', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('On Track', 'On Track'), ('At Risk', 'At Risk'), ('Completed', 'Completed')], max_length=50)),
                ('comments', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='strategy.keyactivity')),
            ],
        ),
        migrations.AddField(
            model_name='keyactivity',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='strategy.strategicobjective'),
        ),
    ]
